name: Benchmarks

permissions:
  contents: read
  id-token: write # for OpenID Connect authentication with CodSpeed

on:
  workflow_dispatch:

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: codspeed-macro
    services:
      kafka:
        image: confluentinc/cp-kafka:8.0.0
        ports:
          - 9092:9092
        env:
          KAFKA_NODE_ID: "1"
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
          KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://127.0.0.1:9092"
          KAFKA_PROCESS_ROLES: "broker,controller"
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_BROKER_ID: "1"
          KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
          KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
          KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
          KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
          CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
      rabbitmq:
        image: rabbitmq:3.13-alpine
        ports:
          - 5672:5672
      nats:
        image: diementros/nats:js
        ports:
          - 4222:4222
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          version: "latest"
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.13"
      - name: Install Dependencies
        run: |
          uv pip install --system --group optionals --group testing .
      - name: Install Pydantic v2
        run: uv pip install --system --prerelease=disallow "pydantic>=2.0.0,<3.0.0"
      - name: Run the benchmarks
        uses: CodSpeedHQ/action@4296e51e7041e24dadb86d1d6e8b9320d223dbe8 # v5.0.3
        with:
          mode: walltime
          run: uv run pytest benchmarks/ --codspeed
          token: ${{ secrets.CODSPEED_TOKEN }}
