name: Build Documentation

on:
  workflow_dispatch: null
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:  # zizmor: ignore[artipacked]
          fetch-depth: 0
          token: ${{ secrets.AUTOMERGE_TOKEN }}
      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          version: "latest"
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          set -ux
          uv pip install --system --group dev -e .
          uv pip uninstall --system email-validator # This is to fix broken link in docs

      - name: Install Just
        uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0
        with:
          just-version: 1.42.4

      - name: Build API Reference
        run: just docs-build-api

      - run: echo "VERSION=$(python3 -c 'from importlib.metadata import version; print(".".join(version("faststream").split(".")[:2]))')" >> $GITHUB_ENV
      - run: echo "IS_RC=$(python3 -c 'from importlib.metadata import version; print("rc" in version("faststream"))')" >> $GITHUB_ENV
      - run: echo $VERSION
      - run: echo $IS_RC

      - name: Configure Git user
        run: |
          git config --local user.email "faststream-actions[bot]@users.noreply.github.com"
          git config --local user.name "faststream-actions[bot]"

      - name: Build docs
        run: |
          if [ "$IS_RC" == "False" ]; then
            cd docs
            mike deploy -F mkdocs.yml --update-aliases $VERSION latest
            mike set-default --allow-empty -F mkdocs.yml latest

            # Doc commits are large, keep only the last one
            git checkout gh-pages
            git reset --soft HEAD~3
          else
            cd docs
            mike deploy -F mkdocs.yml --update-aliases $VERSION

            # Doc commits are large, keep only the last one
            git checkout gh-pages
            git reset --soft HEAD~2
          fi

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          branch: gh-pages
          push_options: "--force"  # force push to stay with clear gh-pages branch history
          commit_message: "docs: deploy docs"
          commit_user_name: faststream-actions[bot]
          commit_user_email: faststream-actions[bot]@users.noreply.github.com
          commit_author: faststream-actions[bot] <faststream-actions[bot]@users.noreply.github.com>
